/    local    8309    redirect    allow
/cgi-bin    local    8303    redirect    allow
/client/clients.xml    local    8309    allow    allow
/folder    local    8309    redirect    allow
/guestFile    local    8309    redirect    allow
/ha-nfc    local    12001    allow    allow
/host    local    8309    redirect    allow
/mob    namedpipe    /var/run/vmware/proxy-mob    redirect    allow
/nfc    local    12000    allow    allow
/screen    local    8309    redirect    allow
/sdk    local    8307    redirect    allow
/sdkTunnel    namedpipetunnel    /var/run/vmware/proxy-sdk-tunnel    allow    reject
/ticket    tickettunnel    /var/run/vmware/ticket/%1    redirect    allow
/tmp    local    8309    redirect    allow
/vpxa    local    8089    reject    allow
/vsan    local    9096    redirect    allow
/vsanperf    localtunnel    9095    allow    reject
/vvold    local    8090    allow    allow
/wsman    local    8889    redirect    allow
