[DEFAULT]
crl_check = false
logdir = <none>
audit_log_local = false
remote_host_max_msg_len = 1024
drop_log_size_kb = 100
x509_strict = false
rotate = 8
audit_log_remote = false
drop_log_rotate = 10
queue_drop_mark = 90
audit_log_dir = <none>
default_timeout = 180
loghost = <none>
check_ssl_certs = true
size = 1024
logdir_unique = false

[vmsyslog]
rotate = 8
size = 1024

