[vmsyslog-logger]
id = fdm
descr = Fdm logs
idents = Fdm
file = fdm
fclass = FileLoggerMessageOnly
nclass = NetworkFilterVmacoreLogLine
onrotate = /var/run/vmware/fdmLogHeader.txt
rotate = 10
size = 5120

