[vmsyslog-logger]
id = hostd
descr = Hostd logs
idents = Hostd
file = hostd
fclass = FileLoggerMessageOnly
nclass = NetworkFilterVmacoreLogLine
onrotate = /var/run/vmware/hostdLogHeader.txt
rotate = 10
size = 10240

