[vmsyslog-logger]
id = vsansystem
descr = vsansystem logs
idents = vsansystem
file = vsansystem
fclass = FileLoggerMessageOnly
nclass = NetworkFilterVmacoreLogLine
onrotate = printf '%%s - last log rotation time, %%s\n' "$(date --utc +%%FT%%T.%%3NZ)" "$(cat /var/run/vmware/vsansystemLogHeader.txt)" | logger -t vsansystem
rotate = 10
size = 10240

