[vmsyslog-logger]

# unique id for this logger
id = rabbitmqproxy

# description of this logger
descr = VMware RabbitMQ host proxy daemon log

# descriptive name for this logger
name = VMware RabbitMQ host proxy daemon log

# idents this logger is interested in
idents = rabbitmqproxy

# output file (e.g. foo == /var/log/foo.log)
file = rabbitmqproxy

# file logger class
fclass = FileLoggerSyslog

# network logger class
nclass = NetworkFilterSyslogTimestamp

# write out the header on log rotation
onrotate = printf '%%s - last log rotation time, %%s\n' "$(date --utc +%%FT%%T.%%3NZ)" "$(cat /var/run/vmware/rabbitmqproxyLogHeader.txt)" | logger -t rabbitmqproxy
