[vmsyslog-logger]

# unique id for this logger
id = sockrelay

# description of this logger
descr = Sockrelay logs

# descriptive name for this logger
name = sockrelay logs

# idents this logger is interested in
idents = sockrelay

# output file (e.g. foo == /var/log/foo.log)
file = sockrelay

# file logger class
fclass = FileLoggerMessageOnly

# network logger class
nclass = NetworkFilterSyslogTimestamp

# max size of the log files, in kb
size = 1024
