[vmsyslog-logger]

# unique id for this logger
id = upitd

# description of this logger
descr = UPITD logs

# descriptive name for this logger
name = upitd logs

# idents this logger is interested in
idents = upitd

# output file (e.g. foo == /var/log/foo.log)
file = upitd

# file logger class
fclass = FileLoggerSyslog

# network logger class
nclass = NetworkFilterSyslogTimestamp

