[vmsyslog-logger]

# unique id for this logger
id = vdfs-proxy

# description of this logger
descr = VDFS proxy logs

# descriptive name for this logger
name = vdfstool proxy logs

# idents this logger is interested in
idents = vdfsd-proxy

# output file (e.g. foo == /var/log/foo.log)
file = vdfsd-proxy

# file logger class
fclass = FileLoggerMessageOnly

# network logger class
nclass = NetworkFilterVmacoreLogLine

# max size of the log files, in kb
size = 10240

