[vmsyslog-logger]
id = vpxa
descr = Vpxa logs
idents = Vpxa
file = vpxa
fclass = FileLoggerMessageOnly
nclass = NetworkFilterVmacoreLogLine
onrotate = /var/run/vmware/vpxaLogHeader.txt
rotate = 20
size = 5120

