[vmsyslog-logger]

# unique id for this logger
id = vsanEsxcli

# description of this logger
descr = vsan esxcli debug

# idents this logger is interested in
idents = vsanEsxcli

# output file (e.g. foo == /var/log/foo.log)
file = vsanEsxcli

# file logger class
fclass = FileLoggerMessageOnly

# network logger class
nclass = NetworkFilterVmacoreLogLine

# how many log files to keep
rotate = 3

# what size to rotate log files (in kb)
size = 5120
