[vmsyslog-logger]

# unique id for this logger
id = vsandpd

# description of this logger
descr = vsandpd logs

# descriptive name for this logger
name = vsandpd logs

# idents this logger is interested in
idents = vsandpd

# output file (e.g. foo == /var/log/foo.log)
file = vsandpd

# file logger class
fclass = FileLoggerMessageOnly

# network logger class
nclass = NetworkFilterVmacoreLogLine

